### ISSUE TITLE
Question on switch

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#9]
1. int main()
{
       int a = 0;
       scanf("%d", &a);
       switch(a)
       {
           case 1:
                     printf("1 is printed\n");
                     break;
           case 2:
                     printf("2 is printed\n");
           case 3: 
                     printf("3 is printed\n");
                     return;
           default:
                     printf("Default case printed\n");            
          
           printf("end of switch\n");
       }
      printf("end of main\n");
      return 0;
}

Provide the output if a is of following values:
1. a = 1
2. a = 2
3. a = 3
4. a = 4

/*Explanation needed for each output below*/

/*Explanation needed for each output above*/

2. char ch1 = 'a', ch2  = 'c';
    switch(ch1 + ch2) 

Please explain whether this kind of passing option to switch is correct. If correct, then provide the reason on what values switch case accepts?

**Comment by prachigithubsharma** [comment]
1) 
1 is printed //after printing this break statement is encountered
end of main //it is printed as it is outside the switch case
2)
2 is printed //since 2 was entered
3 is printed //until break is encountered it reads and executes all the statements
3)
3 is printed //since 3 was entered and it returns 
4)
Default case printed //default case is printed 
end of switch 
end of main //it is printed as it is outside the switch case statements
2. it will not throw any kind of error.

**Comment by giripras** [comment]
Good!!
Regarding the reasoning question. Switch accepts int or char values only as the expression inside switch case must evaluate to integral const.
